###############################################################################
#
# (c)opyright 2018-2019, Andreas Pott
# 
# This is the WireX continuous integration (CI) script for the gitlab platform
# Currently two runner are supported for the tags "win32" and "linux"
#
# Remark: As of 24.07.2018, no runner is available to execute the Jobs on the
#         Windows platform. All those jobs
# Remark: job name starting with a dot "." are inactive 
###############################################################################

variables:
  PROJECT_NAME: "WireX"


before_script:
  - echo Starting CI for project %PROJECT_NAME%


stages:
  - build
#  - test
  - deploy


# the following jobs use the linux/gcc platform through the tags 'linux'
build_gcc:
  stage: build
  script:
  - echo Building the linux binaries
  - cmake .
  - make
  tags:
  - linux


# the following jobs build on a windows platform with visual studio, doxygen, latex environment
build_cpp:
  stage: build
  script:
  - echo Release build...
  - ECHO Setup Env Variables for Visual Studio 2015 MSBUILD
  - 'call "%VS140COMNTOOLS%..\..\vc\vcvarsall.bat"' # x86_amd64'
  - cd WireCenter
  - "msbuild WireCenter.2015.sln /p:Configuration=Release /v:m"
  - cd ..
  only:
  - master
  - tags    
  artifacts:
    paths:
    - lib/
    - WireCenter/bin/
    - WiPy/Release/WiPy.pyd
  tags: 
  - win32


.test:
  stage: test
  script:
  - echo Starting tests based on WiPy.
  - copy WiPy\Release\WiPy.pyd WireCenter\bin
  - cd WireCenter\bin\
  - 'python ..\..\PythonScripts\WireCenter_Python\wcUnitTest.py'
  dependencies:
  - build_cpp
  tags:
  - win32


doc:
  stage: build
  script:
  - echo Building LaTeX docu
  - cd doc
  - ps2pdf XmlFileFormatStructure.eps XmlFileFormatStructure-eps-converted-to.pdf
  - pdflatex WireDoc
  - pdflatex WireDoc
  tags: 
  - linux
  artifacts:
    name: WireDoc
    paths: 
    - doc/WireDoc.pdf


.doxygen:
  stage: build
  script:
  - echo Building Doxygen docu as Compiled HTML Help (CHM)
  - cd doc
  - 'call dox.bat'
  tags:
  - win32
  artifacts:
    name: doxygen
    paths:
    - doc/ATLAS.chm


deploy_wirecenter:
  stage: deploy
  script:
  - ECHO Building distributable package of WireCenter
  - mkdir bin
  - cd bin
  - mkdir WireCenter
  - cd ..
  - cd WireCenter
  - 'call deploy.bat'
  tags:
  - win32
  dependencies:
  - build_cpp
  only:
  - master
  - tags  
  artifacts:
    name: WireCenter
    paths:
    - bin/WireCenter/
